### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by merdes** [endroid/EndroidQrCodeBundle#24]
In order to get this bundle working on Symfony 3:

In services.yml

Before:
```
services:
    endroid.qrcode.twig.extension:
        class: Endroid\Bundle\QrCodeBundle\Twig\Extension\QrCodeExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [ @service_container ] ]
````

After:
```
services:
    endroid.qrcode.twig.extension:
        class: Endroid\Bundle\QrCodeBundle\Twig\Extension\QrCodeExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [ '@service_container' ] ]
````
